# Generated by Django 5.1.4 on 2025-01-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_profileupdate_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(upload_to='posts/')),
            ],
        ),
    ]
